Bug 797254 - guile2 fails to build in Windows...
time_rz.c:308: undefined reference to `rpl_mktime'

Patch the gnulib part to correctly handle builds where REPLACE_TIMEGM
is true and REPLACE_MKTIME may or may not be true.

Also switch to building a snapshot from Guile's repo and applying our
patches via jhbuild instead of using a snapshot of a private repo.